version: '3.8'

services:
  simple-rabbitmq:
    image: mcr.microsoft.com/devcontainers/dotnet:0-6.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ..:/workspaces/simple-rabbitmq:cached
    
    networks:
      - simple-rabbitmq-network
      
    command: sleep infinity

networks:
  simple-rabbitmq-network:
    name: simple-rabbitmq-network